### PR TITLE
Adds index to the source struct

### PR DESCRIPTION
**Pull request by akeddy**
Make sure these boxes are checked before submitting the issue:

- [ ] I have provided ways to reproduce the problem this pull request fixes.
- [x] I have added tests (where possible)
- [x] I have done my best to ensure a passing build on CI (both tests and Credo checks)

### CODE REVIEW

**Comment by akeddy** [comment]
I personally use a lot of wildcard searches as I index per day. Adding the index to the returned results allows the docs to be updated etc. more easily.

**Comment by radar** [comment]
Thank you for the PR.

Would you mind updating the tests to assert this field comes through there too? I also suspect the documentation for Document.API (particularly the instructions for defining a struct) will also need to be updated.

**Comment by akeddy** [comment]
I can take a crack at it for sure

**Comment by akeddy** [comment]
committed some tests I'm reasonably confident cover what you asked.

less confident in the documentation changes but am happy for direction.

**Comment by radar** [comment]
Looks great to me. Thank you!

**Comment by radar** [comment]
This has now been released as 3.7.0.

**Comment by oleks** [comment]
> This has now been released as 3.7.0.

We seem to be forgetting to use git tags to mark releases, in addition to pushing them to Hex.

**Comment by akeddy** [comment]
awesome, thanks!

**Pull request merged**
